development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://psclrkemldkkae:8a3e3adafd09793c122dffeb8c468b5ac7f082eda936d156f89331662380b05c@ec2-50-17-207-16.compute-1.amazonaws.com:5432/dat99fngh56ul7
